# Overrides for kube-prometheus-stack
grafana:
  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: true
    size: 2Gi

prometheus:
  prometheusSpec:
    retention: 3d

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 5Gi