# Overrides for kube-prometheus-stack
crds:
  upgradeJob:
    enabled: true

grafana:
  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: true
    size: 2Gi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 3d

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 5Gi