# Overrides for kube-prometheus-stack
crds:
  upgradeJob:
    enabled: true

grafana:
  adminUser: admin
  adminPassword: admin

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

  persistence:
    enabled: true
    size: 2Gi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 3d

    externalUrl: "/prometheus"
    routePrefix: "/prometheus"

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 5Gi